### ISSUE TITLE
update the logo in navbar with new logo

### ISSUE THREAD

**Issue by ishubham21** [DSCRtu/dscrtukota.github.io#11]

**Comment by Chavda-Mitul** [comment]
Hey i want to work on this issue will you plz provide me the new logo

**Comment by ishubham21** [comment]
![GDSC Rajasthan Technical University vertical color](https://user-images.githubusercontent.com/34435822/139709030-c768f821-8e78-487f-ba14-1b2a04d607cf.png)

**Comment by Chavda-Mitul** [comment]
Hey the background is not matching with logo that you provided so what should I do?

**Comment by ishubham21** [comment]
![GDSC_RTU](https://user-images.githubusercontent.com/34435822/139874726-6858f550-c9ff-4c38-b5c8-10537a427568.png)

**Comment by ishubham21** [comment]
![GDSC_RTU](https://user-images.githubusercontent.com/34435822/139874807-821cc4fd-a577-4c73-9def-97db71979eb0.png)
Check this out @Chavda-Mitul

**Comment by Chavda-Mitul** [comment]
have you received my pull request (As I am doing it first time)

**Comment by ishubham21** [comment]
> have you received my pull request (As I am doing it first time)

Yes, @Chavda-Mitul we have received your Pull Request but the problem is - you are working on the issues that were not assigned to you. 
When we are working on any open-source project, the best way to work on any issue is to comment on the issue, wait for the maintainer to assign it to you, and then start working on it. 

This helps us in keeping a track of who is working on which issue. 

To resolve your problem, I have closed the Pull Request created by you. You can use the command git restore (read more about it) to go back to the initial state, and then pull the latest changes to start working on the issue that is assigned to you. 

If it sounds too technical, you can delete your forked copy and then fork this repo again, and then start working once again from scratch.
