### ISSUE TITLE
change the color of footer text to white in workshops page

### ISSUE THREAD

**Issue by ishubham21** [DSCRtu/dscrtukota.github.io#3]

**Comment by khush2706** [comment]
I would like to work on this...

**Comment by anjalikumawat2002** [comment]
can I work on this @ishubham21 boss??

**Comment by ishubham21** [comment]
Assigned @anjalikumawat2002

**Comment by ishubham21** [comment]
Update @anjalikumawat2002 ?

**Comment by anjalikumawat2002** [comment]
> Update @anjalikumawat2002 ?

Boss, I have created a PR
https://github.com/anjalikumawat2002/gdsc-rtu.github.io/pull/1

**Comment by ishubham21** [comment]
> > Update @anjalikumawat2002 ?
> 
> Boss, I have created a PR [anjalikumawat2002#1](https://github.com/anjalikumawat2002/gdsc-rtu.github.io/pull/1)

You have made a PR on your own repository. Please check once again.

**Comment by ishubham21** [comment]
> > Update @anjalikumawat2002 ?
> 
> Boss, I have created a PR [anjalikumawat2002#1](https://github.com/anjalikumawat2002/gdsc-rtu.github.io/pull/1)

Merge the PR on your forked copy and then create a PR for this repository.

**Comment by anjalikumawat2002** [comment]
> > > Update @anjalikumawat2002 ?
> > 
> > 
> > Boss, I have created a PR [anjalikumawat2002#1](https://github.com/anjalikumawat2002/gdsc-rtu.github.io/pull/1)
> 
> Merge the PR on your forked copy and then create a PR for this repository.

okk boss

**Comment by anjalikumawat2002** [comment]
> > > > Update @anjalikumawat2002 ?
> > > 
> > > 
> > > Boss, I have created a PR [anjalikumawat2002#1](https://github.com/anjalikumawat2002/gdsc-rtu.github.io/pull/1)
> > 
> > 
> > Merge the PR on your forked copy and then create a PR for this repository.
> 
> okk boss

https://github.com/GDSC-RTU/gdsc-rtu.github.io/pull/26 
@ishubham21 can you please review my PR?
